import mysql.connector

def get_db_connection():
    return mysql.connector.connect(
        host="127.0.0.1",
        user="root",
        password="",
        database="nne"
    )

def get_database_schema() -> str:
    """
    Dynamically retrieves the schema of the 'nne' database.
    Returns a string formatted as:
    Table: <table_name>
    Columns:
    - <col_name> (<col_type>)
    ...
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    
    schema_str = ""
    
    try:
        # Get all tables
        cursor.execute("SHOW TABLES")
        tables = cursor.fetchall()
        
        for (table_name,) in tables:
            schema_str += f"\nTable: {table_name}\nColumns:\n"
            
            # Get columns for each table
            cursor.execute(f"DESCRIBE {table_name}")
            columns = cursor.fetchall()
            
            for col in columns:
                # col[0] is Field, col[1] is Type
                schema_str += f"- {col[0]} ({col[1]})\n"
                
    except mysql.connector.Error as err:
        schema_str = f"Error retrieving schema: {err}"
        
    finally:
        cursor.close()
        conn.close()
        
    return schema_str

def execute_sql_query(query: str) -> str:
    """
    Executes a raw SQL query generated by the AI.
    Returns the results as a string.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    
    result_str = ""
    
    try:
        # clean the query slightly if needed (remove markdown)
        clean_query = query.replace("```sql", "").replace("```", "").strip()
        
        cursor.execute(clean_query)
        rows = cursor.fetchall()
        
        if not rows:
            return "Query executed successfully but returned no results."
            
        result_str = str(rows)
        
    except mysql.connector.Error as err:
        result_str = f"SQL Execution Error: {err}"
        
    finally:
        cursor.close()
        conn.close()
        
    return result_str
